version: '3.3'
services:
    pharma_gyan:
        command: /bin/bash -c "/usr/bin/supervisord -n -c /etc/supervisord.d/pharma_gyan_web_service.conf"
        ports:
            - '8080:80'
        environment:
            - CURR_ENV=uat
        image: '$TAG'