from pharma_gyan_proj.orm_models.base_model import *

from pharma_gyan_proj.orm_models.promo_code_orm_model import pg_promo_code
from pharma_gyan_proj.orm_models.admin_users_orm_model import pg_admin_users
from pharma_gyan_proj.orm_models.user_permissions_orm_model import pg_user_permissions
from pharma_gyan_proj.orm_models.user_sessions_orm_model import pg_user_sessions
from pharma_gyan_proj.orm_models.content.chapter_orm_model import pg_chapter
from pharma_gyan_proj.orm_models.entity_tag_orm_model import pg_entity_tag