MAX_ALLOWED_PROMO_CODE_NAME_LENGTH = 64
MIN_ALLOWED_PROMO_CODE_NAME_LENGTH = 4

MAX_ALLOWED_PROMO_CODE_LENGTH = 64
MIN_ALLOWED_PROMO_CODE_LENGTH = 4

MAX_ALLOWED_CHAPTER_NAME_LENGTH = 128
MIN_ALLOWED_CHAPTER_NAME_NAME_LENGTH = 4

MAX_ALLOWED_ENTITY_NAME_LENGTH = 64
MIN_ALLOWED_ENTITY_NAME_LENGTH = 4

MAX_ALLOWED_DESCRIPTION_LENGTH = 254
MIN_ALLOWED_DESCRIPTION_LENGTH = 4
